name: bq_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # animation
  lottie: ^1.3.0
  percent_indicator: ^4.0.1
  flutter_slidable: ^1.2.0
  shimmer: ^2.0.0
  # font
  google_fonts: ^2.3.2
  font_awesome_flutter: ^10.1.0
  # state management
  flutter_bloc: ^8.0.1
  # firebase
  firebase_core: ^1.17.0
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  firebase_storage: ^10.2.16
  # utils
  email_validator: ^2.0.1
  image_picker: ^0.8.5+3
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/images/
