class AppStrings {
  static const String welcomeStr = "Hoşgeldin";
  static const String loginStr = "Giriş";
  static const String mailStr = "Mail";
  static const String passwordStr = "Şifre";
  static const String registerStr = "Kayıt Ol";
  static const String nameStr = "Ad";
  static const String surnameStr = "Soyad";
  static const String forgotPasswordStr = "Şifreni mi Unuttun?";
  static const String noAccountStr = "Hesabın yok mu? Kayıt Ol";
  static const String resetPasswordStr = "Şifremi Sıfırla";
  static const String alreadyHaveAccountStr = "Zaten bir hesabım var";
  static const String backToLoginStr = "Giriş Sayfasına Dön";
  static const String booksStr = "Kitaplar";
  static const String editBookStr = "Kitap Düzenle";
  static const String addBookStr = "Kitap Ekle";
  static const String bookNameStr = "Kitap Adı";
  static const String authorStr = "Yazar";
  static const String pageCountStr = "Sayfa Sayısı";
  static const String readPageCountStr = "Okunan Sayfa Sayısı";
  static const String addStr = "Ekle";
  static const String editStr = "Düzenle";
  static const String saveStr = "Kaydet";
  static const String pageNumberStr = "Sayfa Numarası";
  static const String pageNumberQuestStr = "Kaçıncı Sayfadasın?";
  static const String deleteStr = "Sil";
  static const String deleteBookQuest = "Bu kitabı silmek istediğine emin misin?";
  static const String cancelStr = "İptal";
}
